version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-markdown
    versions:
    - 6.0.0
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: raw-loader
    versions:
    - 4.0.2
